name: ballwizard
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drop_shadow: ^0.1.0
  google_fonts: <4.0.5
  flutter_markdown: ^0.6.17+3
  flutter_contentful: ^3.0.5
  json_annotation: ^4.3.0
  provider: ^6.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.1
  firebase_auth: ^4.15.1
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.7
  firebase_storage: ^11.5.4
  path_provider: ^2.1.1
  google_sign_in: ^6.1.6
  twitter_login: ^4.4.0
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.0.0
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logofb.png
    - assets/Russian Criss-Cross.md
    - assets/apple.png
    - assets/facebook.png
    - assets/google.png
